name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action
        with:
          root: /
      - name: connect to ${{ secrets.HOST }} and update source directory (/var/www/jackd.cloud)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/jackd.cloud
            git pull --rebase
